cinemania/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('search/', views.search_movies, name='search'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('<int:movie_id>/comment/', views.create_comment, name='comment'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('categories/<int:category_id>/', views.list_category_movies, name='category_individual'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

movies/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.IntegerField()
    director = models.CharField(max_length=255)
    poster_url = models.URLField(max_length=255, null=True)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} ({self.release_year})'


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    movie = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    movies = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

movies/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'release_year',
            'director',
            'poster_url',
        ]
        labels = {
            'name': 'Título',
            'release_year': 'Data de Lançamento',
            'director': 'Diretor',
            'poster_url': 'URL do Poster',
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .temp_data import movie_data
from django.urls import reverse
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm
from django.views import generic


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'movies/detail.html'
    context_object_name = 'movie'


class PostListView(generic.ListView):
    model = Post
    context_object_name = 'movie_list'
    template_name = 'movies/index.html'


def search_movies(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        movie_list = Post.objects.filter(name__icontains=search_term)
        context = {"movie_list": movie_list}
    return render(request, 'movies/search.html', context)


class PostCreateView(generic.CreateView):
    context_object_name = 'movie'
    form_class = PostForm
    model = Post
    template_class = PostForm
    template_name = "movies/create.html"

    def get_success_url(self):
        return reverse('movies:detail', kwargs={'pk': self.object.id})


class PostUpdateView(generic.UpdateView):
    context_object_name = 'movie'
    form_class = PostForm
    model = Post
    template_class = PostForm
    template_name = "movies/update.html"

    def get_success_url(self):
        return reverse('movies:detail', kwargs={'pk': self.object.id})


class PostDeleteView(generic.DeleteView):
    model = Post
    context_object_name = 'movie'
    template_name = 'movies/delete.html'
    
    def get_success_url(self):
        return reverse('movies:index')


def create_comment(request, movie_id):
    movie = get_object_or_404(Post, pk=movie_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                              text=comment_text,
                              movie=movie)
            comment.save()
            return HttpResponseRedirect(
                reverse('movies:detail', args=(movie_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'movie': movie}
    return render(request, 'movies/comment.html', context)


class CategoryListView(generic.ListView):
    model = Category
    template_name = 'movies/categories.html'


def list_category_movies(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    context = {'category': category}
    return render(request, 'movies/category_individual.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

movies/templates/movies/categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Listas de Categorias</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <h3>{{category.name}}</h3>
        {{category.description}}
        <br>
        <a href="{% url 'movies:category_individual' category.id %}"> Ver Filmes</a>
    </article>
    {% endfor %}
</section>

{% endblock content %}

movies/templates/movies/category_individual.html
{% extends 'base.html' %}

{% block title %}
{{category.name}}
{% endblock title %}

{% block content %}
<h2>{{ category.name }}</h2>
{{ category.description }}
<section class="lista-de-cards">
    {% for movie in category.movies.all %}
    <article class="card">
        <a href="{% url 'movies:detail' movie.id %}"><img src="{{ movie.poster_url }}"
            alt="Poster do filme {{ movie.name}}"></a>
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% endblock content %}

movies/templates/movies/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar Filme {{ movie.name }} ({{ movie.release_year }})</h2>

<form action="{% url 'movies:comment' movie.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'movies:detail' movie.id %}">Voltar para a página do filme</a></p>
{% endblock content %}

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Filme</h2>
<form method="POST" action="{% url 'movies:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

movies/templates/movies/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'movies:delete' movie.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o filme "{{ movie.name }} ({{ movie.release_year }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block title %}
{{ movie.name }} ({{ movie.release_year }})
{% endblock title %}

{% block content %}
<h2>Detalhes do Filme {{ movie.name }} ({{ movie.release_year }})</h2>

<section class="dados-de-filme">
    <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
    <ul>
        <li><b>Título:</b> {{ movie.name | safe}}</li>
        <li><b>Ano de Lançamento:</b> {{ movie.release_year | safe}}</li>
        <li><b>Diretor:</b> {{ movie.director | safe}}</li>
        {% if movie.category_set.all %}
            <li><b>Categorias:</b></li>
            <ul>
            {% for category in movie.category_set.all %}
            <li><a href="{% url 'movies:category_individual' category.id %}"> {{ category.name }}</a></li>
            {% endfor %}
            </ul>
        {% endif %}
        <li><b>Data de Postagem:</b> {{ movie.date | date}}</li>
        <br>
        <li><a href="{% url 'movies:update' movie.id %}">Editar</a></li>
        <li><a href="{% url 'movies:delete' movie.id %}">Apagar</a></li>
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Comentários:</h3>
    </header>
    <ul>
        {% if movie.comment_set.all %}
            {% for comment in movie.comment_set.all|dictsortreversed:"date" %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <i><figcaption>— {{ comment.author }}</i> | <i>{{ comment.date | date}}</i>
                </figure>

                <hr>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para este filme.</p>
        {% endif %}
    </ul>

    <a href="{% url 'movies:comment' movie.pk %}"><button>Adicione seu Comentário</button></a>
</section>


{% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block title %}
Filmes
{% endblock title %}

{% block content %}
<ul>
    <li> Caso esteja procurando um filme específico: <a href="{% url 'movies:search' %}">Buscar</a> </li>
    <li> Caso queira adicionar um filme: <a href="{% url 'movies:create' %}">Adicionar</a> </li>
</ul>
<h2>Lista de Filmes</h2>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <a href="{% url 'movies:detail' movie.id %}"><img src="{{ movie.poster_url }}"
            alt="Poster do filme {{ movie.name}}"></a>
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme.</p>
{% endif %}

{% endblock content %}

movies/templates/movies/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Filmes por Nome</h2>
<form action="{% url 'movies:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <a href="{% url 'movies:detail' movie.id %}"><img src="{{ movie.poster_url }}"
            alt="Poster do filme {{ movie.name}}"></a>
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme para a busca.</p>
{% endif %}

{% endblock content %}

movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Filme {{ movie.name }} ({{ movie.release_year}})</h2>
<form method="POST" action="{% url 'movies:update' movie.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | CineMania
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <div class="logo">
            <a href="{% url 'index' %}"> <img src="https://i.imgur.com/Tiu5CnM.png"> </a>
        </div>
        <nav id="navegacao-principal">
            <a href="{% url 'movies:index' %}">Filmes</a>
            |
            <a href="{% url 'movies:categories' %}">Categorias</a>
            |
            <a href="{% url 'about' %}">Sobre</a>
        </nav>
    </header>

    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>

    <footer id="rodape-principal">
        <p>© Copyright 2021</p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre o Site</h2>
<p>
    Este é um site dinâmico que foi elaborado, utilizando o Django, como requisito
    avaliativo para a disciplina PMR3304 - Sistemas de Informação, no curso de
    Engenharia Mecatrônica da Escola Politécnica da Universidade de São Paulo.
</p>
<h2>Sobre o Autor</h2>
<p>
    Site desenvolvido por Gabriel Antonio Corteletti Tápias, entusiasta de cinema e, atualmente (2021),
    estudante do 3º ano de Engenharia Mecatrônica na EP-USP, NºUSP: 11258210. Informações de contato:
    <a href="https://www.linkedin.com/in/gabriel-corteletti-t%C3%A1pias-98251120b/">LinkedIn</a>
    |
    gabrielcorteletti@usp.br
</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<div class="section" id="introduction">
    <div>
        Bem vindo ao CineMania, o mais novo blog de cinema. Acesse a seção "Filmes" para
        ver os filmes já cadastrados no site. Nesta seção, também estão disponíveis as
        ferramentas para buscar um filme específico e para adicionar um filme novo. Quando
        encontrar o filme que deseja, acesse a página dele para escrever seu comentário e
        ler os comentários de outros usuários. Além disso, os filmes também são separados por
        categorias. Assim, acesse a seção "Categorias" para ver as categorias disponíveis e
        selecione uma delas para ver os filmes inclusos nela.
    </div>
    <br>
    <div>
        <a href="{% url 'index' %}"> <img src="https://i.imgur.com/07nkOA1.jpg"></a>
    </div>
</div>
{% endblock content %}